// Diagnostic — prove whether dart:ui can decode known-valid PNG bytes.
//
// Purpose:
//   Image.memory() internally calls ui.instantiateImageCodec().
//   If the codec succeeds here, the bytes are provably valid.
//   Any failure after this point is a rendering-layer issue, not a bytes issue.
//
// The PNG bytes here were generated by Python's zlib+struct pipeline:
//   python -c "
//     import zlib, struct
//     def make_png_chunk(name, data):
//         chunk = name + data
//         crc = zlib.crc32(chunk) & 0xffffffff
//         return struct.pack('>I', len(data)) + chunk + struct.pack('>I', crc)
//     ihdr = make_png_chunk(b'IHDR', struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0))
//     raw_row = b'\x00' + b'\xff\xff\xff'
//     compressed = zlib.compress(raw_row, 9)
//     idat = make_png_chunk(b'IDAT', compressed)
//     iend = make_png_chunk(b'IEND', b'')
//     png = b'\x89PNG\r\n\x1a\n' + ihdr + idat + iend
//     print(list(png))
//   "
//   Output: [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82,
//            0, 0, 0, 1, 0, 0, 0, 1, 8, 2, 0, 0, 0, 144, 119, 83, 222, 0, 0,
//            0, 12, 73, 68, 65, 84, 120, 218, 99, 248, 255, 255, 63, 0, 5,
//            254, 2, 254, 51, 18, 149, 20, 0, 0, 0, 0, 73, 69, 78, 68, 174,
//            66, 96, 130]

import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';

// Python-generated valid 1×1 white RGB PNG — 69 bytes.
final Uint8List kValidPng = Uint8List.fromList([
  137, 80, 78, 71, 13, 10, 26, 10,          // PNG signature
  0, 0, 0, 13, 73, 72, 68, 82,              // IHDR chunk
  0, 0, 0, 1, 0, 0, 0, 1,                  // width=1, height=1
  8, 2, 0, 0, 0,                            // 8-bit RGB, no interlace
  144, 119, 83, 222,                        // IHDR CRC (python-computed)
  0, 0, 0, 12, 73, 68, 65, 84,             // IDAT chunk (12 bytes)
  120, 218, 99, 248, 255, 255, 63, 0, 5, 254, 2, 254, // IDAT zlib data
  51, 18, 149, 20,                          // IDAT CRC
  0, 0, 0, 0, 73, 69, 78, 68,              // IEND chunk (0 bytes)
  174, 66, 96, 130,                         // IEND CRC
]);

void main() {
  group('Image.memory / dart:ui codec evidence', () {

    test('PROOF: PNG signature bytes are correct', () {
      final sig = kValidPng.sublist(0, 8);
      debugPrint('[EVIDENCE] Byte length: ${kValidPng.length}');
      debugPrint('[EVIDENCE] Format: PNG (verified by signature [137,80,78,71,13,10,26,10])');
      debugPrint('[EVIDENCE] First 8 bytes: $sig');
      expect(sig, equals([137, 80, 78, 71, 13, 10, 26, 10]),
          reason: 'PNG magic bytes must be present');
    });

    test('PROOF: dart:ui can decode Python-generated PNG bytes', () async {
      debugPrint('[EVIDENCE] Byte length: ${kValidPng.length}');
      debugPrint('[EVIDENCE] Format: PNG (Python-generated via zlib+struct)');

      bool decodeSucceeded = false;
      int imageWidth = 0;
      int imageHeight = 0;
      String? decodeError;

      try {
        final codec = await ui.instantiateImageCodec(kValidPng);
        final frame = await codec.getNextFrame();
        final image = frame.image;
        imageWidth = image.width;
        imageHeight = image.height;
        decodeSucceeded = true;
        image.dispose();
      } catch (e) {
        decodeError = e.toString();
      }

      debugPrint('[EVIDENCE] dart:ui decode succeeded: $decodeSucceeded');
      debugPrint('[EVIDENCE] Image dimensions: ${imageWidth}x$imageHeight');
      if (decodeError != null) {
        debugPrint('[EVIDENCE] dart:ui decode error: $decodeError');
      }

      // This is the critical assertion.
      // If this passes: valid PNG bytes CAN be decoded. Any Image.memory
      //   failure on web is a rendering issue, not a bytes issue.
      // If this fails: our test PNG is still malformed (we need different bytes).
      expect(decodeSucceeded, isTrue,
          reason: 'dart:ui must be able to decode this Python-generated PNG. '
              'Error: $decodeError');
    });

    test('PROOF: 5-byte fake data from trace test is NOT valid image data', () async {
      final fakeBytes = Uint8List.fromList([1, 2, 3, 4, 5]);
      debugPrint('[EVIDENCE] Fake bytes length: ${fakeBytes.length}');
      debugPrint('[EVIDENCE] Fake bytes signature: ${fakeBytes.sublist(0, 4)}');
      debugPrint('[EVIDENCE] Expected PNG signature: [137, 80, 78, 71]');
      debugPrint('[EVIDENCE] MATCH: false — prior trace test used invalid image data');

      bool fakeDecodeFailed = false;
      try {
        await ui.instantiateImageCodec(fakeBytes);
      } catch (e) {
        fakeDecodeFailed = true;
        debugPrint('[EVIDENCE] Fake bytes decode result: FAILED — $e');
      }

      expect(fakeDecodeFailed, isTrue,
          reason: 'Fake bytes must fail. This confirms the trace test '
              '"Invalid image data" error came from the test fixture, '
              'NOT from the actual file picker bytes.');
    });

  });
}
