import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Immutable snapshot of a single document from the Firestore [badges]
/// collection.
///
/// ## Firestore document structure
///
/// ```
/// badges/{badgeId}            ← document ID auto-generated by Firestore
///   name:        String       — display label, e.g. "New Arrival"
///   slug:        String       — URL-safe, unique, e.g. "new-arrival"
///   color:       String       — hex colour string, e.g. "#FF5733"
///   icon:        String       — Material icon name, e.g. "local_fire_department"
///   isActive:    bool
///   sortOrder:   int
///   createdAt:   Timestamp
///   updatedAt:   Timestamp
/// ```
///
/// The document ID is stored in [id] via [DocumentSnapshot.id].
/// It is NOT stored as a separate field inside the document body, and
/// [toMap] therefore excludes it.
///
/// ## Timestamp handling
///
/// Mirrors [CategoryModel]: timestamps written via `FieldValue.serverTimestamp()`
/// in the repository, never from a client-side [DateTime].
/// Missing/malformed timestamp fields fall back to epoch and emit a debug
/// warning so malformed documents are visible during development.
class BadgeModel {
  const BadgeModel({
    required this.id,
    required this.name,
    required this.slug,
    required this.color,
    required this.icon,
    required this.isActive,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Firestore auto-generated document ID. Never stored as a field inside
  /// the document body.
  final String id;

  /// Display label shown to customers, e.g. `"New Arrival"`.
  final String name;

  /// URL-safe slug, e.g. `"new-arrival"`. Unique within the collection.
  final String slug;

  /// Hex colour string used to render the badge chip, e.g. `"#FF5733"`.
  /// Stored as a plain string; parsing is the UI layer's responsibility.
  final String color;

  /// Material icon name string, e.g. `"local_fire_department"`.
  /// The UI resolves this to an [IconData] at render time.
  final String icon;

  /// Whether the badge is currently active (available to assign to products).
  final bool isActive;

  /// Controls ordering in badge lists. Lower values appear first.
  final int sortOrder;

  /// When this badge document was created (server timestamp).
  final DateTime createdAt;

  /// When this badge document was last modified (server timestamp).
  final DateTime updatedAt;

  // ── Serialization ──────────────────────────────────────────────────────────

  /// Creates a [BadgeModel] from a Firestore document snapshot.
  ///
  /// [snapshot] must exist; callers ([BadgeRepository]) are responsible for
  /// checking [DocumentSnapshot.exists] before calling this factory.
  factory BadgeModel.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    final data = snapshot.data() ?? {};
    final id = snapshot.id;

    DateTime safeTimestamp(String field) {
      final raw = data[field];
      if (raw is Timestamp) return raw.toDate();
      debugPrint(
        '[BadgeModel] WARNING: document $id is missing or has '
        'wrong type for "$field". Falling back to epoch.',
      );
      return DateTime.fromMillisecondsSinceEpoch(0);
    }

    return BadgeModel(
      id: id,
      name: data['name'] as String? ?? '',
      slug: data['slug'] as String? ?? '',
      color: data['color'] as String? ?? '',
      icon: data['icon'] as String? ?? '',
      isActive: data['isActive'] as bool? ?? true,
      sortOrder: (data['sortOrder'] as num?)?.toInt() ?? 0,
      createdAt: safeTimestamp('createdAt'),
      updatedAt: safeTimestamp('updatedAt'),
    );
  }

  /// Converts this model to a plain map suitable for Firestore writes.
  ///
  /// [id] is intentionally excluded — it is the document ID, not a field.
  /// Use [FieldValue.serverTimestamp()] directly in the repository for
  /// create/update operations rather than calling [toMap].
  Map<String, dynamic> toMap() => {
    'name': name,
    'slug': slug,
    'color': color,
    'icon': icon,
    'isActive': isActive,
    'sortOrder': sortOrder,
    'createdAt': Timestamp.fromDate(createdAt),
    'updatedAt': Timestamp.fromDate(updatedAt),
  };

  /// Returns a copy of this model with the specified fields replaced.
  BadgeModel copyWith({
    String? id,
    String? name,
    String? slug,
    String? color,
    String? icon,
    bool? isActive,
    int? sortOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return BadgeModel(
      id: id ?? this.id,
      name: name ?? this.name,
      slug: slug ?? this.slug,
      color: color ?? this.color,
      icon: icon ?? this.icon,
      isActive: isActive ?? this.isActive,
      sortOrder: sortOrder ?? this.sortOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() =>
      'BadgeModel('
      'id: $id, '
      'name: $name, '
      'slug: $slug, '
      'isActive: $isActive, '
      'sortOrder: $sortOrder'
      ')';
}
