name: shared_widgets
description: The shared_widgets package for the enterprise eCommerce platform.
version: 0.0.1
environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
