import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Immutable snapshot of a single document from the Firestore [categories]
/// collection.
///
/// ## Firestore document structure
///
/// ```
/// categories/{categoryId}        ← document ID auto-generated by Firestore
///   name:        String
///   slug:        String
///   description: String
///   imageUrl:    String
///   isActive:    bool
///   sortOrder:   int
///   createdAt:   Timestamp
///   updatedAt:   Timestamp
/// ```
///
/// The document ID is stored in [id] via [DocumentSnapshot.id].
/// It is NOT stored as a separate field inside the document body, and
/// [toMap] therefore excludes it.
///
/// ## Timestamp handling
///
/// [createdAt] and [updatedAt] are written to Firestore using
/// `FieldValue.serverTimestamp()` (never a client-side [DateTime]).
/// When read back, they arrive as [Timestamp] objects and are converted
/// to [DateTime] via [Timestamp.toDate].
///
/// If a timestamp field is missing (e.g. a document written before this
/// schema existed), the fallback is `DateTime.fromMillisecondsSinceEpoch(0)`
/// and a debug warning is printed so the issue is visible during development.
class CategoryModel {
  const CategoryModel({
    required this.id,
    required this.name,
    required this.slug,
    required this.description,
    required this.imageUrl,
    required this.isActive,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Firestore auto-generated document ID. Never stored as a field inside
  /// the document body.
  final String id;

  /// Display name, e.g. `"Electronics"`.
  final String name;

  /// URL-safe slug, e.g. `"electronics"`. Unique within the collection.
  final String slug;

  /// Human-readable description of the category.
  final String description;

  /// URL of the category hero image. Empty string when not yet set.
  final String imageUrl;

  /// Whether the category is currently active (visible to customers).
  final bool isActive;

  /// Controls ordering in category lists. Lower values appear first.
  final int sortOrder;

  /// When this category document was created (server timestamp).
  final DateTime createdAt;

  /// When this category document was last modified (server timestamp).
  final DateTime updatedAt;

  // ── Serialization ──────────────────────────────────────────────────────────

  /// Creates a [CategoryModel] from a Firestore document snapshot.
  ///
  /// [snapshot] must exist; callers ([CategoryRepository]) are responsible for
  /// checking [DocumentSnapshot.exists] before calling this factory.
  ///
  /// Missing or wrongly-typed primitive fields fall back to safe empty
  /// defaults. Missing timestamp fields fall back to epoch and emit a
  /// debug warning so malformed documents do not silently pass unnoticed.
  factory CategoryModel.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    final data = snapshot.data() ?? {};
    final id = snapshot.id;

    // ── Timestamps (fail-visible fallback) ───────────────────────────────────
    DateTime safeTimestamp(String field) {
      final raw = data[field];
      if (raw is Timestamp) return raw.toDate();
      // Malformed or absent — log so developers can spot the issue.
      debugPrint(
        '[CategoryModel] WARNING: document $id is missing or has '
        'wrong type for "$field". Falling back to epoch.',
      );
      return DateTime.fromMillisecondsSinceEpoch(0);
    }

    return CategoryModel(
      id: id,
      name: data['name'] as String? ?? '',
      slug: data['slug'] as String? ?? '',
      description: data['description'] as String? ?? '',
      imageUrl: data['imageUrl'] as String? ?? '',
      isActive: data['isActive'] as bool? ?? true,
      sortOrder: (data['sortOrder'] as num?)?.toInt() ?? 0,
      createdAt: safeTimestamp('createdAt'),
      updatedAt: safeTimestamp('updatedAt'),
    );
  }

  /// Converts this model to a plain map suitable for Firestore writes.
  ///
  /// [id] is intentionally excluded — it is the document ID, not a field.
  ///
  /// Timestamps are stored as [Timestamp] objects (not [DateTime]) to
  /// remain consistent with Firestore's native type system.
  ///
  /// Note: For create/update operations, use [FieldValue.serverTimestamp()]
  /// directly in the repository rather than calling [toMap]; [toMap] is
  /// primarily used for testing and debugging.
  Map<String, dynamic> toMap() => {
    'name': name,
    'slug': slug,
    'description': description,
    'imageUrl': imageUrl,
    'isActive': isActive,
    'sortOrder': sortOrder,
    'createdAt': Timestamp.fromDate(createdAt),
    'updatedAt': Timestamp.fromDate(updatedAt),
  };

  /// Returns a copy of this model with the specified fields replaced.
  ///
  /// Genuinely useful in [CategoryController] for optimistic UI updates
  /// and building partial update maps.
  CategoryModel copyWith({
    String? id,
    String? name,
    String? slug,
    String? description,
    String? imageUrl,
    bool? isActive,
    int? sortOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return CategoryModel(
      id: id ?? this.id,
      name: name ?? this.name,
      slug: slug ?? this.slug,
      description: description ?? this.description,
      imageUrl: imageUrl ?? this.imageUrl,
      isActive: isActive ?? this.isActive,
      sortOrder: sortOrder ?? this.sortOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() =>
      'CategoryModel('
      'id: $id, '
      'name: $name, '
      'slug: $slug, '
      'isActive: $isActive, '
      'sortOrder: $sortOrder'
      ')';
}

/// Helper class to represent a category image candidate within the form flow.
class PickedCategoryImage {
  final String? url;
  final Uint8List? bytes;
  final String? name;

  PickedCategoryImage.fromUrl(this.url)
    : bytes = null,
      name = null;
  PickedCategoryImage.fromFile({required this.bytes, required this.name})
    : url = null;

  bool get isRemote => url != null;
}
