import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// Immutable snapshot of a single document from the Firestore [products]
/// collection.
///
/// ## Firestore document structure
///
/// ```
/// products/{productId}        ← document ID auto-generated by Firestore
///   name:           String
///   slug:           String
///   description:    String
///   categoryId:     String
///   badgeIds:       List<String>
///   sku:            String
///   price:          double
///   comparePrice:   double?
///   costPrice:      double?
///   stock:          int
///   isActive:       bool
///   isFeatured:     bool
///   thumbnailImage: String?
///   images:         List<String>
///   createdAt:      Timestamp
///   updatedAt:      Timestamp
/// ```
///
/// The document ID is stored in [id] via [DocumentSnapshot.id].
/// It is NOT stored as a separate field inside the document body, and
/// [toMap] therefore excludes it.
///
/// ## Timestamp handling
///
/// [createdAt] and [updatedAt] are written to Firestore using
/// `FieldValue.serverTimestamp()`. When read back, they arrive as [Timestamp]
/// objects and are converted to [DateTime] via [Timestamp.toDate].
///
/// If a timestamp field is missing (e.g. a document written before this
/// schema existed), the fallback is `DateTime.fromMillisecondsSinceEpoch(0)`
/// and a debug warning is printed.
class ProductModel {
  const ProductModel({
    required this.id,
    required this.name,
    required this.slug,
    required this.description,
    required this.categoryId,
    required this.badgeIds,
    required this.sku,
    required this.price,
    this.comparePrice,
    this.costPrice,
    required this.stock,
    required this.isActive,
    required this.isFeatured,
    this.thumbnailImage,
    required this.images,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Firestore auto-generated document ID. Never stored as a field inside
  /// the document body.
  final String id;

  /// Display name of the product.
  final String name;

  /// URL-safe unique slug of the product.
  final String slug;

  /// Human-readable description of the product.
  final String description;

  /// The document ID of the associated Category.
  final String categoryId;

  /// Document IDs of associated Badges.
  final List<String> badgeIds;

  /// Stock Keeping Unit code.
  final String sku;

  /// Current selling price.
  final double price;

  /// Price before sale/discount. Null if not on sale.
  final double? comparePrice;

  /// Internal acquisition cost. Null if not specified.
  final double? costPrice;

  /// Quantity available in stock.
  final int stock;

  /// Whether the product is active and visible to customers.
  final bool isActive;

  /// Whether the product is featured in marketing displays.
  final bool isFeatured;

  /// Download URL for the product's dedicated thumbnail image.
  final String? thumbnailImage;

  /// List of download URLs for the product's gallery images.
  final List<String> images;

  /// When this product was created (server timestamp).
  final DateTime createdAt;

  /// When this product was last modified (server timestamp).
  final DateTime updatedAt;

  // ── Computed helpers ────────────────────────────────────────────────────────

  /// Best available preview image for table/card displays.
  ///
  /// Priority:
  /// 1. [thumbnailImage] if present and non-empty.
  /// 2. First entry in [images] if the gallery is non-empty.
  /// 3. `null` — caller should show a placeholder icon.
  String? get displayImageUrl {
    if (thumbnailImage != null && thumbnailImage!.isNotEmpty) {
      return thumbnailImage;
    }
    if (images.isNotEmpty) {
      return images.first;
    }
    return null;
  }

  // ── Serialization ──────────────────────────────────────────────────────────

  /// Creates a [ProductModel] from a Firestore document snapshot.
  ///
  /// [snapshot] must exist; callers are responsible for checking [DocumentSnapshot.exists]
  /// before calling this factory.
  ///
  /// Missing or wrongly-typed fields fall back to safe defaults. Missing timestamp
  /// fields fall back to epoch and emit a debug warning.
  factory ProductModel.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    final data = snapshot.data() ?? {};
    final id = snapshot.id;

    // ── Timestamps (fail-visible fallback) ───────────────────────────────────
    DateTime safeTimestamp(String field) {
      final raw = data[field];
      if (raw is Timestamp) return raw.toDate();
      debugPrint(
        '[ProductModel] WARNING: document $id is missing or has '
        'wrong type for "$field". Falling back to epoch.',
      );
      return DateTime.fromMillisecondsSinceEpoch(0);
    }

    // Parse image fields
    final parsedThumb = data['thumbnailImage'] as String?;
    final parsedImages =
        (data['images'] as List?)?.map((e) => e.toString()).toList() ?? <String>[];

    return ProductModel(
      id: id,
      name: data['name'] as String? ?? '',
      slug: data['slug'] as String? ?? '',
      description: data['description'] as String? ?? '',
      categoryId: data['categoryId'] as String? ?? '',
      badgeIds:
          (data['badgeIds'] as List?)?.map((e) => e.toString()).toList() ?? [],
      sku: data['sku'] as String? ?? '',
      price: (data['price'] as num?)?.toDouble() ?? 0.0,
      comparePrice: (data['comparePrice'] as num?)?.toDouble(),
      costPrice: (data['costPrice'] as num?)?.toDouble(),
      stock: (data['stock'] as num?)?.toInt() ?? 0,
      isActive: data['isActive'] as bool? ?? true,
      isFeatured: data['isFeatured'] as bool? ?? false,
      thumbnailImage: parsedThumb,
      images: parsedImages,
      createdAt: safeTimestamp('createdAt'),
      updatedAt: safeTimestamp('updatedAt'),
    );
  }

  /// Converts this model to a plain map suitable for Firestore writes.
  ///
  /// [id] is intentionally excluded — it is the document ID, not a field.
  ///
  /// Timestamps are stored as [Timestamp] objects to remain consistent with
  /// Firestore's native type system.
  Map<String, dynamic> toMap() => {
    'name': name,
    'slug': slug,
    'description': description,
    'categoryId': categoryId,
    'badgeIds': badgeIds,
    'sku': sku,
    'price': price,
    'comparePrice': comparePrice,
    'costPrice': costPrice,
    'stock': stock,
    'isActive': isActive,
    'isFeatured': isFeatured,
    'thumbnailImage': thumbnailImage,
    'images': images,
    'createdAt': Timestamp.fromDate(createdAt),
    'updatedAt': Timestamp.fromDate(updatedAt),
  };

  /// Returns a copy of this model with the specified fields replaced.
  ProductModel copyWith({
    String? id,
    String? name,
    String? slug,
    String? description,
    String? categoryId,
    List<String>? badgeIds,
    String? sku,
    double? price,
    double? comparePrice,
    double? costPrice,
    int? stock,
    bool? isActive,
    bool? isFeatured,
    String? thumbnailImage,
    List<String>? images,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return ProductModel(
      id: id ?? this.id,
      name: name ?? this.name,
      slug: slug ?? this.slug,
      description: description ?? this.description,
      categoryId: categoryId ?? this.categoryId,
      badgeIds: badgeIds ?? this.badgeIds,
      sku: sku ?? this.sku,
      price: price ?? this.price,
      comparePrice: comparePrice ?? this.comparePrice,
      costPrice: costPrice ?? this.costPrice,
      stock: stock ?? this.stock,
      isActive: isActive ?? this.isActive,
      isFeatured: isFeatured ?? this.isFeatured,
      thumbnailImage: thumbnailImage ?? this.thumbnailImage,
      images: images ?? this.images,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() =>
      'ProductModel('
      'id: $id, '
      'name: $name, '
      'slug: $slug, '
      'sku: $sku, '
      'price: $price, '
      'isActive: $isActive, '
      'isFeatured: $isFeatured'
      ')';
}

/// Helper class to represent product image candidates within the form flow.
class PickedProductImage {
  final String? url;
  final Uint8List? bytes;
  final String? name;
  final String? localPath;

  PickedProductImage.fromUrl(this.url)
    : bytes = null,
      name = null,
      localPath = null;
  PickedProductImage.fromFile({
    required this.bytes,
    required this.name,
    this.localPath,
  }) : url = null;

  bool get isRemote => url != null;
}

/// Helper class to represent a product thumbnail candidate within the form flow.
class PickedThumbnail {
  final String? url;
  final Uint8List? bytes;
  final String? name;

  PickedThumbnail.fromUrl(this.url)
    : bytes = null,
      name = null;
  PickedThumbnail.fromFile({required this.bytes, required this.name})
    : url = null;

  bool get isRemote => url != null;
}
